/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    EmptyState: typeof import('./src/components/EmptyState.vue')['default']
    ErrorState: typeof import('./src/components/ErrorState.vue')['default']
    LoadingState: typeof import('./src/components/LoadingState.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    NutAvatar: typeof import('@nutui/nutui-taro')['Avatar']
    NutBadge: typeof import('@nutui/nutui-taro')['Badge']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutCell: typeof import('@nutui/nutui-taro')['Cell']
    NutCellGroup: typeof import('@nutui/nutui-taro')['CellGroup']
    NutCheckbox: typeof import('@nutui/nutui-taro')['Checkbox']
    NutDialog: typeof import('@nutui/nutui-taro')['Dialog']
    NutGrid: typeof import('@nutui/nutui-taro')['Grid']
    NutGridItem: typeof import('@nutui/nutui-taro')['GridItem']
    NutIcon: typeof import('@nutui/nutui-taro')['Icon']
    NutIndicator: typeof import('@nutui/nutui-taro')['Indicator']
    NutInputNumber: typeof import('@nutui/nutui-taro')['InputNumber']
    NutList: typeof import('@nutui/nutui-taro')['List']
    NutLoading: typeof import('@nutui/nutui-taro')['Loading']
    NutNavbar: typeof import('@nutui/nutui-taro')['Navbar']
    NutOverlay: typeof import('@nutui/nutui-taro')['Overlay']
    NutSearchbar: typeof import('@nutui/nutui-taro')['Searchbar']
    NutSteps: typeof import('@nutui/nutui-taro')['Steps']
    NutSwiper: typeof import('@nutui/nutui-taro')['Swiper']
    NutSwiperItem: typeof import('@nutui/nutui-taro')['SwiperItem']
    NutTabbar: typeof import('@nutui/nutui-taro')['Tabbar']
    NutTabbarItem: typeof import('@nutui/nutui-taro')['TabbarItem']
    NutTabpane: typeof import('@nutui/nutui-taro')['Tabpane']
    NutTabPane: typeof import('@nutui/nutui-taro')['TabPane']
    NutTabs: typeof import('@nutui/nutui-taro')['Tabs']
    ProductCard: typeof import('./src/components/ProductCard.vue')['default']
  }
}
